   <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDlWwxN6bwNheL1s5jwQxzKlZMo_HTTNAQ&v=3.exp&sensor=false"></script>
	 <script src="<%=application.getContextPath()%>/js/vendor/jquery-library.js"></script>
   <script src="<%=application.getContextPath()%>/js/vendor/bootstrap.min.js"></script>
   <script src="<%=application.getContextPath()%>/js/bootstrap-select.min.js"></script>
   <script src="<%=application.getContextPath()%>/js/jquery-scrolltofixed.js"></script>
   <script src="<%=application.getContextPath()%>/js/owl.carousel.min.js"></script>
   <script src="<%=application.getContextPath()%>/js/jquery.mmenu.all.js"></script>
   <script src="<%=application.getContextPath()%>/js/packery.pkgd.min.js"></script>
   <script src="<%=application.getContextPath()%>/js/jquery.vide.min.js"></script>
   <script src="<%=application.getContextPath()%>/js/scrollbar.min.js"></script>
   <script src="<%=application.getContextPath()%>/js/prettyPhoto.js"></script>
   <script src="<%=application.getContextPath()%>/js/countdown.js"></script>
   <script src="<%=application.getContextPath()%>/js/parallax.js"></script>
   <script src="<%=application.getContextPath()%>/js/gmap3.js"></script>
   <script src="<%=application.getContextPath()%>/js/main.js"></script>
